version: "3"
services:
  database:
    image: "mongo"
    container_name: "myContainer"
    environment:
      - MONGO_INITDB_DATABASE=myDatabase
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
